apiVersion: v2
name: todo-app
description: A Helm chart for Todo Chatbot application with Kubernetes deployment
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - todo
  - chatbot
  - kubernetes
  - fastapi
  - nextjs
maintainers:
  - name: Todo Team
